class ScrumAgent < Formula
  include Language::Python::Virtualenv

  desc "AI-powered Scrum Master — decomposes projects into epics, stories, tasks, and sprint plans"
  homepage "https://github.com/omardin14/scrum-planning-ai-agent"
  url "https://files.pythonhosted.org/packages/source/s/scrum-agent/scrum_agent-1.0.0.tar.gz"
  sha256 "ef20b228179b4178f63a0703a54b956310965537a9e04e1ed84e95b081d9f27d"
  license "MIT"

  depends_on "python@3.12"

  # Resource stanzas for dependencies will be generated by homebrew-pypi-poet
  # after the package is published to PyPI. Run:
  #   pip install homebrew-pypi-poet
  #   poet scrum-agent
  # and paste the output here.

  def install
    virtualenv_install_with_resources
  end

  def caveats
    <<~EOS
      To get started, configure your API key:
        scrum-agent --setup

      Then launch the interactive planner:
        scrum-agent

      For headless/CI usage:
        scrum-agent --non-interactive --description "Build a todo app" --output json
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/scrum-agent --version")
    assert_match "scrum-agent", shell_output("#{bin}/scrum-agent --help")
  end
end
